// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: companyModel.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_companyModel_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_companyModel_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_companyModel_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_companyModel_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_companyModel_2eproto;
class CompanyModel;
struct CompanyModelDefaultTypeInternal;
extern CompanyModelDefaultTypeInternal _CompanyModel_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CompanyModel* Arena::CreateMaybeMessage<::CompanyModel>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class CompanyModel final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CompanyModel) */ {
 public:
  inline CompanyModel() : CompanyModel(nullptr) {}
  ~CompanyModel() override;
  explicit constexpr CompanyModel(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CompanyModel(const CompanyModel& from);
  CompanyModel(CompanyModel&& from) noexcept
    : CompanyModel() {
    *this = ::std::move(from);
  }

  inline CompanyModel& operator=(const CompanyModel& from) {
    CopyFrom(from);
    return *this;
  }
  inline CompanyModel& operator=(CompanyModel&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CompanyModel& default_instance() {
    return *internal_default_instance();
  }
  static inline const CompanyModel* internal_default_instance() {
    return reinterpret_cast<const CompanyModel*>(
               &_CompanyModel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CompanyModel& a, CompanyModel& b) {
    a.Swap(&b);
  }
  inline void Swap(CompanyModel* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CompanyModel* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CompanyModel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CompanyModel>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CompanyModel& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CompanyModel& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CompanyModel* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CompanyModel";
  }
  protected:
  explicit CompanyModel(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kJuristicAddrFieldNumber = 2,
    kNameFieldNumber = 3,
    kSortOfActivityFieldNumber = 4,
    kEstYearFieldNumber = 1,
    kExtEconomActivityFieldNumber = 5,
  };
  // required string juristicAddr = 2;
  bool has_juristicaddr() const;
  private:
  bool _internal_has_juristicaddr() const;
  public:
  void clear_juristicaddr();
  const std::string& juristicaddr() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_juristicaddr(ArgT0&& arg0, ArgT... args);
  std::string* mutable_juristicaddr();
  PROTOBUF_NODISCARD std::string* release_juristicaddr();
  void set_allocated_juristicaddr(std::string* juristicaddr);
  private:
  const std::string& _internal_juristicaddr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_juristicaddr(const std::string& value);
  std::string* _internal_mutable_juristicaddr();
  public:

  // required string name = 3;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional string sortOfActivity = 4;
  bool has_sortofactivity() const;
  private:
  bool _internal_has_sortofactivity() const;
  public:
  void clear_sortofactivity();
  const std::string& sortofactivity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sortofactivity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sortofactivity();
  PROTOBUF_NODISCARD std::string* release_sortofactivity();
  void set_allocated_sortofactivity(std::string* sortofactivity);
  private:
  const std::string& _internal_sortofactivity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sortofactivity(const std::string& value);
  std::string* _internal_mutable_sortofactivity();
  public:

  // required int32 estYear = 1;
  bool has_estyear() const;
  private:
  bool _internal_has_estyear() const;
  public:
  void clear_estyear();
  int32_t estyear() const;
  void set_estyear(int32_t value);
  private:
  int32_t _internal_estyear() const;
  void _internal_set_estyear(int32_t value);
  public:

  // optional bool extEconomActivity = 5;
  bool has_exteconomactivity() const;
  private:
  bool _internal_has_exteconomactivity() const;
  public:
  void clear_exteconomactivity();
  bool exteconomactivity() const;
  void set_exteconomactivity(bool value);
  private:
  bool _internal_exteconomactivity() const;
  void _internal_set_exteconomactivity(bool value);
  public:

  // @@protoc_insertion_point(class_scope:CompanyModel)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr juristicaddr_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sortofactivity_;
  int32_t estyear_;
  bool exteconomactivity_;
  friend struct ::TableStruct_companyModel_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CompanyModel

// required int32 estYear = 1;
inline bool CompanyModel::_internal_has_estyear() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool CompanyModel::has_estyear() const {
  return _internal_has_estyear();
}
inline void CompanyModel::clear_estyear() {
  estyear_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline int32_t CompanyModel::_internal_estyear() const {
  return estyear_;
}
inline int32_t CompanyModel::estyear() const {
  // @@protoc_insertion_point(field_get:CompanyModel.estYear)
  return _internal_estyear();
}
inline void CompanyModel::_internal_set_estyear(int32_t value) {
  _has_bits_[0] |= 0x00000008u;
  estyear_ = value;
}
inline void CompanyModel::set_estyear(int32_t value) {
  _internal_set_estyear(value);
  // @@protoc_insertion_point(field_set:CompanyModel.estYear)
}

// required string juristicAddr = 2;
inline bool CompanyModel::_internal_has_juristicaddr() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CompanyModel::has_juristicaddr() const {
  return _internal_has_juristicaddr();
}
inline void CompanyModel::clear_juristicaddr() {
  juristicaddr_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CompanyModel::juristicaddr() const {
  // @@protoc_insertion_point(field_get:CompanyModel.juristicAddr)
  return _internal_juristicaddr();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CompanyModel::set_juristicaddr(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 juristicaddr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:CompanyModel.juristicAddr)
}
inline std::string* CompanyModel::mutable_juristicaddr() {
  std::string* _s = _internal_mutable_juristicaddr();
  // @@protoc_insertion_point(field_mutable:CompanyModel.juristicAddr)
  return _s;
}
inline const std::string& CompanyModel::_internal_juristicaddr() const {
  return juristicaddr_.Get();
}
inline void CompanyModel::_internal_set_juristicaddr(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  juristicaddr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* CompanyModel::_internal_mutable_juristicaddr() {
  _has_bits_[0] |= 0x00000001u;
  return juristicaddr_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* CompanyModel::release_juristicaddr() {
  // @@protoc_insertion_point(field_release:CompanyModel.juristicAddr)
  if (!_internal_has_juristicaddr()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = juristicaddr_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (juristicaddr_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    juristicaddr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void CompanyModel::set_allocated_juristicaddr(std::string* juristicaddr) {
  if (juristicaddr != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  juristicaddr_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), juristicaddr,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (juristicaddr_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    juristicaddr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:CompanyModel.juristicAddr)
}

// required string name = 3;
inline bool CompanyModel::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CompanyModel::has_name() const {
  return _internal_has_name();
}
inline void CompanyModel::clear_name() {
  name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& CompanyModel::name() const {
  // @@protoc_insertion_point(field_get:CompanyModel.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CompanyModel::set_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:CompanyModel.name)
}
inline std::string* CompanyModel::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:CompanyModel.name)
  return _s;
}
inline const std::string& CompanyModel::_internal_name() const {
  return name_.Get();
}
inline void CompanyModel::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* CompanyModel::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000002u;
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* CompanyModel::release_name() {
  // @@protoc_insertion_point(field_release:CompanyModel.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void CompanyModel::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:CompanyModel.name)
}

// optional string sortOfActivity = 4;
inline bool CompanyModel::_internal_has_sortofactivity() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CompanyModel::has_sortofactivity() const {
  return _internal_has_sortofactivity();
}
inline void CompanyModel::clear_sortofactivity() {
  sortofactivity_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& CompanyModel::sortofactivity() const {
  // @@protoc_insertion_point(field_get:CompanyModel.sortOfActivity)
  return _internal_sortofactivity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CompanyModel::set_sortofactivity(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 sortofactivity_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:CompanyModel.sortOfActivity)
}
inline std::string* CompanyModel::mutable_sortofactivity() {
  std::string* _s = _internal_mutable_sortofactivity();
  // @@protoc_insertion_point(field_mutable:CompanyModel.sortOfActivity)
  return _s;
}
inline const std::string& CompanyModel::_internal_sortofactivity() const {
  return sortofactivity_.Get();
}
inline void CompanyModel::_internal_set_sortofactivity(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  sortofactivity_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* CompanyModel::_internal_mutable_sortofactivity() {
  _has_bits_[0] |= 0x00000004u;
  return sortofactivity_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* CompanyModel::release_sortofactivity() {
  // @@protoc_insertion_point(field_release:CompanyModel.sortOfActivity)
  if (!_internal_has_sortofactivity()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  auto* p = sortofactivity_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sortofactivity_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    sortofactivity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void CompanyModel::set_allocated_sortofactivity(std::string* sortofactivity) {
  if (sortofactivity != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  sortofactivity_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sortofactivity,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sortofactivity_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    sortofactivity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:CompanyModel.sortOfActivity)
}

// optional bool extEconomActivity = 5;
inline bool CompanyModel::_internal_has_exteconomactivity() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool CompanyModel::has_exteconomactivity() const {
  return _internal_has_exteconomactivity();
}
inline void CompanyModel::clear_exteconomactivity() {
  exteconomactivity_ = false;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool CompanyModel::_internal_exteconomactivity() const {
  return exteconomactivity_;
}
inline bool CompanyModel::exteconomactivity() const {
  // @@protoc_insertion_point(field_get:CompanyModel.extEconomActivity)
  return _internal_exteconomactivity();
}
inline void CompanyModel::_internal_set_exteconomactivity(bool value) {
  _has_bits_[0] |= 0x00000010u;
  exteconomactivity_ = value;
}
inline void CompanyModel::set_exteconomactivity(bool value) {
  _internal_set_exteconomactivity(value);
  // @@protoc_insertion_point(field_set:CompanyModel.extEconomActivity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_companyModel_2eproto
